"use client";
import { Alert,Button,Card,Field,Input,Select,Spinner,Textarea } from "@/components/ui";
import { EMPTY_CUSTOMER,type CustomerRecord,type CustomerKind } from "@/lib/customers";
import { getStore,isDemoMode } from "@/lib/store";
import { useCallback,useEffect,useMemo,useState,type FormEvent } from "react";
const fresh=():CustomerRecord=>({...EMPTY_CUSTOMER,id:crypto.randomUUID(),createdAt:"",updatedAt:""});
export default function CustomersPage(){
 const [rows,setRows]=useState<CustomerRecord[]|null>(null),[editing,setEditing]=useState<CustomerRecord|null>(null),[q,setQ]=useState(""),[filter,setFilter]=useState("all"),[error,setError]=useState(""),[saving,setSaving]=useState(false);
 const load=useCallback(async()=>{try{setRows(await getStore().listCustomers())}catch(e){setError(e instanceof Error?e.message:"Could not load contacts.");setRows([])}},[]);useEffect(()=>{void load()},[load]);
 const filtered=useMemo(()=>{const n=q.trim().toLowerCase();return(rows||[]).filter(c=>(filter==="all"||c.kind===filter)&&(!n||[c.name,c.phone,c.email,c.city,c.source].join(" ").toLowerCase().includes(n)))},[rows,q,filter]);
 async function save(e:FormEvent){e.preventDefault();if(!editing)return;setSaving(true);setError("");try{await getStore().saveCustomer({...editing,name:editing.name.trim()});setEditing(null);await load()}catch(e){setError(e instanceof Error?e.message:"Could not save contact.")}finally{setSaving(false)}}
 async function remove(c:CustomerRecord){if(!confirm(`Remove ${c.name} from contacts?`))return;try{await getStore().removeCustomer(c.id);await load()}catch(e){setError(e instanceof Error?e.message:"Could not remove contact.")}}
 const list=rows||[];const leads=list.filter(c=>c.kind==="lead").length;const followups=list.filter(c=>c.nextFollowUp&&c.nextFollowUp<=new Date().toISOString().slice(0,10)).length;
 return <main className="mx-auto max-w-7xl px-4 py-6 sm:px-6"><div className="mb-6 flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-neutral-400">Relationship management</p><h1 className="mt-1 text-2xl font-bold tracking-tight">Customers &amp; leads</h1><p className="text-sm text-neutral-500">Keep contact details, enquiry source, and follow-up reminders together.</p></div><Button onClick={()=>setEditing(fresh())}>+ Add contact</Button></div>
 {isDemoMode()&&<div className="mb-5"><Alert kind="info"><b>Demo mode.</b> Contacts are saved in this browser only.</Alert></div>}{error&&<div className="mb-5"><Alert>{error}</Alert></div>}
 <div className="mb-5 grid grid-cols-2 gap-3 sm:grid-cols-3"><Metric label="Contacts" value={list.length}/><Metric label="Leads" value={leads}/><Metric label="Follow-ups due" value={followups}/></div>
 <Card className="!p-0"><div className="flex flex-col gap-3 border-b border-neutral-100 p-4 sm:flex-row"><Input placeholder="Search name, phone, email…" className="sm:max-w-md" value={q} onChange={e=>setQ(e.target.value)}/><Select className="sm:max-w-48" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All contacts</option><option value="lead">Leads</option><option value="customer">Customers</option></Select><span className="self-center text-xs text-neutral-400 sm:ml-auto">{rows?`${filtered.length} of ${rows.length}`:""}</span></div>
 {rows===null?<div className="px-4"><Spinner label="Loading contacts…"/></div>:filtered.length===0?<div className="px-6 py-16 text-center"><p className="text-neutral-600">{list.length?"No contacts match your search.":"No contacts recorded yet."}</p><p className="mt-1 text-sm text-neutral-400">Add leads and customers to keep follow-ups from getting lost.</p>{!list.length&&<Button className="mt-4" onClick={()=>setEditing(fresh())}>Add first contact</Button>}</div>:<div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left text-xs uppercase tracking-wider text-neutral-400"><th className="px-4 py-3 font-medium">Name</th><th className="px-4 py-3 font-medium">Phone / email</th><th className="hidden px-4 py-3 font-medium sm:table-cell">Type / source</th><th className="px-4 py-3 font-medium">Next follow-up</th><th className="px-4 py-3"/></tr></thead><tbody className="divide-y divide-neutral-100">{filtered.map(c=><tr key={c.id} className="hover:bg-neutral-50"><td className="px-4 py-3"><div className="font-semibold">{c.name}</div><div className="text-xs text-neutral-500">{[c.city,c.address].filter(Boolean).join(" · ")}</div></td><td className="px-4 py-3"><div>{c.phone||"—"}</div><div className="text-xs text-neutral-500">{c.email}</div></td><td className="hidden px-4 py-3 sm:table-cell"><span className="capitalize">{c.kind}</span><div className="text-xs text-neutral-500">{c.source||"—"}</div></td><td className="px-4 py-3"><span className={c.nextFollowUp&&c.nextFollowUp<=new Date().toISOString().slice(0,10)?"font-semibold text-amber-700":""}>{c.nextFollowUp||"—"}</span></td><td className="whitespace-nowrap px-4 py-3 text-right"><button onClick={()=>setEditing({...c})} className="rounded-md px-2 py-1 text-neutral-600 hover:bg-neutral-100">Edit</button><button onClick={()=>void remove(c)} className="rounded-md px-2 py-1 text-red-600 hover:bg-red-50">Remove</button></td></tr>)}</tbody></table></div>}</Card>
 {editing&&<div className="fixed inset-0 z-50 flex items-start justify-center overflow-y-auto bg-black/50 p-3 sm:items-center sm:p-6" onMouseDown={e=>{if(e.target===e.currentTarget&&!saving)setEditing(null)}}><div className="my-3 w-full max-w-2xl rounded-2xl bg-white shadow-2xl"><div className="flex justify-between border-b border-neutral-100 px-5 py-4"><div><h2 className="text-lg font-bold">{list.some(c=>c.id===editing.id)?"Edit contact":"Add contact"}</h2><p className="text-sm text-neutral-500">Basic relationship details and follow-up.</p></div><button aria-label="Close" onClick={()=>setEditing(null)} className="rounded-lg px-3 py-1 text-xl text-neutral-400 hover:bg-neutral-100">×</button></div><form onSubmit={save} className="px-5 py-5"><div className="grid grid-cols-1 gap-4 sm:grid-cols-2"><Field label="Full name *"><Input required value={editing.name} onChange={e=>setEditing({...editing,name:e.target.value})}/></Field><Field label="Contact type"><Select value={editing.kind} onChange={e=>setEditing({...editing,kind:e.target.value as CustomerKind})}><option value="lead">Lead</option><option value="customer">Customer</option></Select></Field><Field label="Phone"><Input type="tel" value={editing.phone} onChange={e=>setEditing({...editing,phone:e.target.value})}/></Field><Field label="Email"><Input type="email" value={editing.email} onChange={e=>setEditing({...editing,email:e.target.value})}/></Field><Field label="Address"><Input value={editing.address} onChange={e=>setEditing({...editing,address:e.target.value})}/></Field><Field label="City / region"><Input value={editing.city} onChange={e=>setEditing({...editing,city:e.target.value})}/></Field><Field label="Enquiry source"><Input value={editing.source} onChange={e=>setEditing({...editing,source:e.target.value})} placeholder="Referral, website, walk-in…"/></Field><Field label="Next follow-up"><Input type="date" value={editing.nextFollowUp} onChange={e=>setEditing({...editing,nextFollowUp:e.target.value})}/></Field></div><div className="mt-4"><Field label="Notes"><Textarea rows={3} value={editing.notes} onChange={e=>setEditing({...editing,notes:e.target.value})}/></Field></div><div className="mt-6 flex flex-col-reverse gap-2 border-t border-neutral-100 pt-4 sm:flex-row sm:justify-end"><Button type="button" variant="secondary" onClick={()=>setEditing(null)} disabled={saving}>Cancel</Button><Button disabled={saving}>{saving?"Saving…":"Save contact"}</Button></div></form></div></div>}
 </main>
}
function Metric({label,value}:{label:string;value:number}){return <div className="rounded-xl border border-neutral-200 bg-white p-4 shadow-sm"><div className="text-xs font-medium uppercase tracking-wider text-neutral-500">{label}</div><div className="mt-1 text-2xl font-bold tabular-nums">{value}</div></div>}
