"use client";

import { Alert, Button, Card, Field, Input, Select, Spinner, Textarea } from "@/components/ui";
import { DEAL_STAGE_LABEL, DEAL_TYPE_LABEL, type DealRecord, type DealStage, type DealType } from "@/lib/deals";
import { formatMoney } from "@/lib/format";
import { getStore, isDemoMode } from "@/lib/store";
import type { StockVehicle } from "@/lib/stock";
import { useCallback, useEffect, useMemo, useState, type FormEvent } from "react";
import Link from "next/link";

function freshDeal(): DealRecord {
  return { id: crypto.randomUUID(), dealNo: "", type: "retail_sale", stage: "enquiry", vehicleId: "", vehicleLabel: "", customerName: "", customerPhone: "", customerEmail: "", dealDate: new Date().toISOString().slice(0,10), currency: "USD", salePrice: 0, amountPaid: 0, tradeInMake: "", tradeInModel: "", tradeInYear: "", tradeInVin: "", tradeInCondition: "", tradeInValue: 0, notes: "", createdAt: "", updatedAt: "" };
}
function balance(d: DealRecord) { return Math.max(0, d.salePrice - (d.type === "trade_in_swap" ? d.tradeInValue : 0) - d.amountPaid); }

export default function SalesPage() {
  const [deals,setDeals]=useState<DealRecord[]|null>(null); const [vehicles,setVehicles]=useState<StockVehicle[]>([]);
  const [editing,setEditing]=useState<DealRecord|null>(null); const [error,setError]=useState(""); const [saving,setSaving]=useState(false); const [q,setQ]=useState(""); const [filter,setFilter]=useState("all");
  const load=useCallback(async()=>{try{const [d,v]=await Promise.all([getStore().listDeals(),getStore().listVehicles()]);setDeals(d);setVehicles(v);}catch(e){setError(e instanceof Error?e.message:"Could not load sales.");setDeals([]);}},[]);
  useEffect(()=>{void load();},[load]);
  const filtered=useMemo(()=>{const needle=q.toLowerCase().trim();return(deals||[]).filter(d=>(filter==="all"||d.stage===filter)&&(!needle||[d.dealNo,d.customerName,d.customerPhone,d.vehicleLabel,d.tradeInVin].join(" ").toLowerCase().includes(needle)));},[deals,q,filter]);
  async function save(e:FormEvent){e.preventDefault();if(!editing)return;setSaving(true);setError("");try{const selected=vehicles.find(v=>v.id===editing.vehicleId);const data={...editing,dealNo:editing.dealNo.trim()||`DS-${new Date().getFullYear()}-${String((deals||[]).length+1).padStart(3,"0")}`,vehicleLabel:selected?[selected.year,selected.make,selected.model,selected.trim].filter(Boolean).join(" "):editing.vehicleLabel};await getStore().saveDeal(data);setEditing(null);await load();}catch(e){setError(e instanceof Error?e.message:"Could not save deal.");}finally{setSaving(false);}}
  async function remove(d:DealRecord){if(!confirm(`Delete deal ${d.dealNo || "draft"}?`))return;try{await getStore().removeDeal(d.id);await load();}catch(e){setError(e instanceof Error?e.message:"Could not delete deal.");}}
  const rows=deals||[];const open=rows.filter(d=>["enquiry","reserved","in_progress"].includes(d.stage)).length;const complete=rows.filter(d=>d.stage==="completed").length;const outstanding=rows.filter(d=>d.stage!=="cancelled").reduce((sum,d)=>sum+balance(d),0);
  return <main className="mx-auto max-w-7xl px-4 py-6 sm:px-6">
    <div className="mb-6 flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-neutral-400">Dealership operations</p><h1 className="mt-1 text-2xl font-bold tracking-tight">Sales &amp; deals</h1><p className="text-sm text-neutral-500">Track enquiries, reservations, sales and vehicle swaps in one pipeline.</p></div><Button onClick={()=>setEditing(freshDeal())}>+ New deal</Button></div>
    {isDemoMode()&&<div className="mb-5"><Alert kind="info"><b>Demo mode.</b> Deals are stored in this browser only. Connect Supabase for shared team records.</Alert></div>}{error&&<div className="mb-5"><Alert>{error}</Alert></div>}
    <div className="mb-5 grid grid-cols-2 gap-3 lg:grid-cols-4"><Metric label="Total deals" value={rows.length}/><Metric label="Open pipeline" value={open}/><Metric label="Completed" value={complete}/><Metric label="Outstanding" value={formatMoney(outstanding,rows[0]?.currency||"USD")}/></div>
    <Card className="!p-0"><div className="flex flex-col gap-3 border-b border-neutral-100 p-4 sm:flex-row"><Input className="sm:max-w-md" placeholder="Search deal, customer, vehicle…" value={q} onChange={e=>setQ(e.target.value)}/><Select className="sm:max-w-52" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All stages</option>{Object.entries(DEAL_STAGE_LABEL).map(([k,v])=><option key={k} value={k}>{v}</option>)}</Select><span className="self-center text-xs text-neutral-400 sm:ml-auto">{deals?`${filtered.length} of ${deals.length}`:""}</span></div>
      {deals===null?<div className="px-4"><Spinner label="Loading deals…"/></div>:filtered.length===0?<div className="px-6 py-16 text-center"><p className="text-neutral-600">{rows.length?"No deals match your search.":"No deals recorded yet."}</p><p className="mt-1 text-sm text-neutral-400">Create a deal to start tracking a customer sale or swap.</p>{!rows.length&&<Button className="mt-4" onClick={()=>setEditing(freshDeal())}>Create first deal</Button>}</div>:<div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left text-xs uppercase tracking-wider text-neutral-400"><th className="px-4 py-3 font-medium">Deal</th><th className="px-4 py-3 font-medium">Customer</th><th className="hidden px-4 py-3 font-medium md:table-cell">Vehicle</th><th className="px-4 py-3 font-medium">Stage</th><th className="hidden px-4 py-3 text-right font-medium sm:table-cell">Balance</th><th className="px-4 py-3"/></tr></thead><tbody className="divide-y divide-neutral-100">{filtered.map(d=><tr key={d.id} className="hover:bg-neutral-50"><td className="whitespace-nowrap px-4 py-3"><div className="font-semibold">{d.dealNo||"Draft"}</div><div className="text-xs text-neutral-500">{DEAL_TYPE_LABEL[d.type]} · {d.dealDate}</div></td><td className="px-4 py-3"><div className="font-medium">{d.customerName||"—"}</div><div className="text-xs text-neutral-500">{d.customerPhone}</div></td><td className="hidden px-4 py-3 md:table-cell">{d.vehicleLabel||"Vehicle not selected"}</td><td className="px-4 py-3"><StageBadge stage={d.stage}/></td><td className="hidden whitespace-nowrap px-4 py-3 text-right tabular-nums sm:table-cell">{formatMoney(balance(d),d.currency)}</td><td className="whitespace-nowrap px-4 py-3 text-right"><Link href={`/invoices/new?deal=${encodeURIComponent(d.id)}`} className="rounded-md px-2 py-1 text-neutral-600 hover:bg-neutral-100">Invoice</Link><button onClick={()=>setEditing({...d})} className="rounded-md px-2 py-1 text-neutral-600 hover:bg-neutral-100">Edit</button><button onClick={()=>void remove(d)} className="rounded-md px-2 py-1 text-red-600 hover:bg-red-50">Delete</button></td></tr>)}</tbody></table></div>}</Card>
    {editing&&<div className="fixed inset-0 z-50 flex items-start justify-center overflow-y-auto bg-black/50 p-3 sm:items-center sm:p-6" onMouseDown={e=>{if(e.target===e.currentTarget&&!saving)setEditing(null);}}><div className="my-3 w-full max-w-3xl rounded-2xl bg-white shadow-2xl sm:my-8"><div className="flex items-start justify-between border-b border-neutral-100 px-5 py-4 sm:px-6"><div><h2 className="text-lg font-bold">{rows.some(d=>d.id===editing.id)?"Edit deal":"Create deal"}</h2><p className="text-sm text-neutral-500">Record the customer, vehicle and financial outline of the transaction.</p></div><button aria-label="Close" onClick={()=>setEditing(null)} className="rounded-lg px-3 py-1 text-xl text-neutral-400 hover:bg-neutral-100">×</button></div>
      <form onSubmit={save} className="max-h-[75vh] overflow-y-auto px-5 py-5 sm:px-6"><SectionTitle>Deal details</SectionTitle><div className="grid grid-cols-1 gap-4 sm:grid-cols-3"><Field label="Deal number"><Input value={editing.dealNo} onChange={e=>setEditing({...editing,dealNo:e.target.value})} placeholder="Auto-generate if blank"/></Field><Field label="Deal type"><Select value={editing.type} onChange={e=>setEditing({...editing,type:e.target.value as DealType})}>{Object.entries(DEAL_TYPE_LABEL).map(([k,v])=><option key={k} value={k}>{v}</option>)}</Select></Field><Field label="Stage"><Select value={editing.stage} onChange={e=>setEditing({...editing,stage:e.target.value as DealStage})}>{Object.entries(DEAL_STAGE_LABEL).map(([k,v])=><option key={k} value={k}>{v}</option>)}</Select></Field><Field label="Deal date"><Input type="date" value={editing.dealDate} onChange={e=>setEditing({...editing,dealDate:e.target.value})}/></Field><Field label="Stock vehicle"><Select value={editing.vehicleId} onChange={e=>setEditing({...editing,vehicleId:e.target.value})}><option value="">Select a vehicle</option>{vehicles.map(v=><option key={v.id} value={v.id}>{[v.stockNo,v.year,v.make,v.model].filter(Boolean).join(" · ")}</option>)}</Select></Field><Field label="Customer name *"><Input required value={editing.customerName} onChange={e=>setEditing({...editing,customerName:e.target.value})}/></Field><Field label="Phone"><Input type="tel" value={editing.customerPhone} onChange={e=>setEditing({...editing,customerPhone:e.target.value})}/></Field><Field label="Email"><Input type="email" value={editing.customerEmail} onChange={e=>setEditing({...editing,customerEmail:e.target.value})}/></Field></div>
      <SectionTitle>Price &amp; payment</SectionTitle><div className="grid grid-cols-1 gap-4 sm:grid-cols-3"><Field label="Sale price"><Input type="number" min="0" step="0.01" value={editing.salePrice||""} onChange={e=>setEditing({...editing,salePrice:Number(e.target.value)})}/></Field><Field label="Currency"><Select value={editing.currency} onChange={e=>setEditing({...editing,currency:e.target.value as DealRecord["currency"]})}><option>USD</option><option>NGN</option><option>EUR</option><option>GBP</option></Select></Field><Field label="Amount paid to date"><Input type="number" min="0" step="0.01" value={editing.amountPaid||""} onChange={e=>setEditing({...editing,amountPaid:Number(e.target.value)})}/></Field></div>
      {editing.type==="trade_in_swap"&&<><SectionTitle>Trade-in vehicle</SectionTitle><div className="grid grid-cols-1 gap-4 sm:grid-cols-3"><Field label="Make"><Input value={editing.tradeInMake} onChange={e=>setEditing({...editing,tradeInMake:e.target.value})}/></Field><Field label="Model"><Input value={editing.tradeInModel} onChange={e=>setEditing({...editing,tradeInModel:e.target.value})}/></Field><Field label="Year"><Input value={editing.tradeInYear} onChange={e=>setEditing({...editing,tradeInYear:e.target.value})}/></Field><Field label="VIN / chassis"><Input value={editing.tradeInVin} onChange={e=>setEditing({...editing,tradeInVin:e.target.value.toUpperCase()})}/></Field><Field label="Condition"><Input value={editing.tradeInCondition} onChange={e=>setEditing({...editing,tradeInCondition:e.target.value})}/></Field><Field label="Agreed trade-in value"><Input type="number" min="0" step="0.01" value={editing.tradeInValue||""} onChange={e=>setEditing({...editing,tradeInValue:Number(e.target.value)})}/></Field></div></>}
      <div className="mt-4 rounded-lg bg-neutral-50 p-4"><div className="flex justify-between text-sm"><span className="text-neutral-600">Customer balance after trade-in and payments</span><strong>{formatMoney(balance(editing),editing.currency)}</strong></div></div><SectionTitle>Notes</SectionTitle><Field label="Internal notes"><Textarea rows={3} value={editing.notes} onChange={e=>setEditing({...editing,notes:e.target.value})} placeholder="Follow-up, handover requirements, deal notes…"/></Field>
      <div className="mt-6 flex flex-col-reverse gap-2 border-t border-neutral-100 pt-4 sm:flex-row sm:justify-end"><Button type="button" variant="secondary" onClick={()=>setEditing(null)} disabled={saving}>Cancel</Button><Button type="submit" disabled={saving}>{saving?"Saving…":"Save deal"}</Button></div></form></div></div>}
  </main>;
}
function Metric({label,value}:{label:string;value:string|number}){return <div className="rounded-xl border border-neutral-200 bg-white p-4 shadow-sm"><div className="text-xs font-medium uppercase tracking-wider text-neutral-500">{label}</div><div className="mt-1 text-xl font-bold tabular-nums">{value}</div></div>}
function SectionTitle({children}:{children:string}){return <h3 className="mb-3 mt-5 border-b border-neutral-100 pb-2 text-xs font-bold uppercase tracking-widest text-neutral-500 first:mt-0">{children}</h3>}
function StageBadge({stage}:{stage:DealStage}){const styles:Record<DealStage,string>={enquiry:"bg-sky-50 text-sky-700 ring-sky-200",reserved:"bg-amber-50 text-amber-700 ring-amber-200",in_progress:"bg-violet-50 text-violet-700 ring-violet-200",completed:"bg-emerald-50 text-emerald-700 ring-emerald-200",cancelled:"bg-neutral-100 text-neutral-600 ring-neutral-200"};return <span className={`inline-flex whitespace-nowrap rounded-full px-2.5 py-0.5 text-xs font-medium ring-1 ${styles[stage]}`}>{DEAL_STAGE_LABEL[stage]}</span>}
